### ISSUE TITLE
考虑是否可以添加「翻译快捷键」

### ISSUE THREAD

**Issue by redfrogotr** [chengfengfengwang/lingo-link#10]
因为我在看一篇英文文章时，不太喜欢在页面显示图标（个人感觉很影响阅读体验，应该也有其他人会这么觉得）。此时，如果我还想继续使用翻译服务的话，我需要右键，然后再点击翻译，这里额外多了一次点击。所以，看作者是否可以考虑加个翻译快捷键选项。

另外，这个插件确实很好用，虽然还有一些小bug，希望它可以更好。💪

**Comment by chengfengfengwang** [comment]
好，谢谢你的建议，我会考虑的，有bug可以随便提issue哦～

**Comment by redfrogotr** [comment]
邮件已收到，我会尽快阅读的 :-)

**Comment by chengfengfengwang** [comment]
Completed #11

**Comment by redfrogotr** [comment]
试了下，体验非常好👍

**Comment by redfrogotr** [comment]
邮件已收到，我会尽快阅读的 :-)
