### ISSUE TITLE
点了发音按钮无声音，请问怎么处理

### ISSUE THREAD

**Issue by tucoo** [chengfengfengwang/lingo-link#17]
<img width="378" alt="1" src="https://github.com/user-attachments/assets/8d7f6c9f-c8d2-4c5b-bf84-b6f8384aa47d">

**Comment by chengfengfengwang** [comment]
是在某个网站上不能发音还是都不能发音？windows系统吗?

**Comment by tucoo** [comment]
都不能发音，windows系统。

**Comment by chengfengfengwang** [comment]
> 都不能发音，windows系统。

好的，什么浏览器？

**Comment by tucoo** [comment]
大佬，是换皮chrome,cent Browser;win10 22H2。
