### ISSUE TITLE
自建的服务不能用

### ISSUE THREAD

**Issue by cwt8805** [chengfengfengwang/lingo-link#4]
自建的服务，接口和OpenAI一致，没有使用key
用的是这个https://github.com/aurora-develop/Duck2api
另外URL填到OpenAI Translator插件中是可以用的

**Comment by chengfengfengwang** [comment]
[complete](https://github.com/chengfengfengwang/lingo-link/tree/4-%E8%87%AA%E5%BB%BA%E7%9A%84%E6%9C%8D%E5%8A%A1%E4%B8%8D%E8%83%BD%E7%94%A8)
